module.exports = {
    'project_name':'express-mvc-generator',
	'adminname': 'Rajaram',
	'adminmail': 'test@gmail.com',
	'adminemail': 'akash.patel@innvonix.com',
	'host':"http://127.0.0.1:8084",
	//'host':"http://localhost:8080",
	'email_smtp_host':'smtp.gmail.com',
	'email_smtp_port':587,
	"smtp_from_email":"innvonix2016@gmail.com",
	"smtp_from_name":"express-mvc-generator",
	"alert_email":"aler@email.com",
	"alert_email_name":"Aler Name",
	"blog_url":"http://revstance.co/index.php/wp-json/wp/v2/posts/",
	'token_price':"0.05",
};